# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  projects: "**/*.csproj"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: "sonarcloud"
      organization: "vmartos"
      scannerMode: "MSBuild"
      projectKey: "vicmaeg_onvif-discovery"
      projectVersion:
      extraProperties: |
        sonar.exclusions=**/bin/**/*,**/obj/**/*,OnvifDiscovery/Client/OnvifUdpClient.cs
        sonar.language=cs
        sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/cov.opencover.xml

  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: '8.0.x'

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: "$(projects)"

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: "**/*.csproj"
      arguments: "--configuration $(buildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      arguments: "--configuration $(buildConfiguration) --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../cov"

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: "300"
